---
title: "Kibera"
output: html_document
date: "2025-06-02"
---

Link to Git repo: https://github.com/nktang05/kibera.git

Link to Analysis: https://nktang05.github.io/kibera/KiberaAnalysis.html


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(mlr3learners) 
require(kknn)  
require(class)
require(ggplot2)
library(mlr3)
library(mlr3viz)
library(ggplot2)
library(data.table)
library(sqldf)
library(codebookr)
library(codebook)
library(dplyr)
library(haven)
library(labelled)
```


### Data Cleaning

```{r}
# read in data
setwd("~/Desktop/GRIT/Kibera")
data <- fread("~/Desktop/GRIT/Kibera/originalCsv/kibera_values_data.csv", header = TRUE)

```


```{r}
# get rid on unnecessary data columns
data$StartDate<- NULL
data$EndDate<- NULL
data$Status<- NULL
data$IPAddress<- NULL
data$Progress<- NULL
data$'Duration (in seconds)'<- NULL
data$Finished<- NULL
data$ RecordedDate<- NULL
data$ResponseId<- NULL
data$RecipientLastName<- NULL
data$RecipientFirstName<- NULL
data$RecipientEmail<- NULL
data$ExternalReference<- NULL
data$LocationLatitude<- NULL
data$LocationLongitude<- NULL
data$DistributionChannel<- NULL
data$UserLanguage<- NULL
data$"2.11_7_TEXT"<- NULL
data$"2.13_7_TEXT"<- NULL
data$"2.20_5_TEXT"<- NULL
data$"3.2_8_TEXT"<- NULL
data$"3.16_6_TEXT"<- NULL
data$"4.21_5_TEXT"<- NULL
data$"5.1_5_TEXT"<- NULL
data$"5.12_6_TEXT"<- NULL


#set aside variable labels
variable_labels <- as.character(unlist(data[1, ]))
# drop non data rows
data <- data[-c(1, 2), ]

# change names of
names(data) <- ifelse(grepl("^[0-9]", names(data)),
                      paste0("x", names(data)),
                      names(data))

```




```{r}
# make var numeric
numericVars <- c("x1.1", "x1.2", "x1.3", "x2.1", "x3.1_1_TEXT", "x3.9" )
for (col in numericVars) {
  data[[col]] <- as.numeric(as.character(data[[col]]))
}

# make var date
data$x1.4 <- as.Date(data$x1.4, format = "%d/%m/%Y")

# make var string
charVars <- c("x2.5_5_TEXT" , "x2.7_6_TEXT", "x2.10_8_TEXT", "x2.12_10_TEXT", "x2.14_5_TEXT", "x2.16_7_TEXT", "x2.21_9_TEXT", "x3.3_7_TEXT", "x3.13_8_TEXT", 
              "x3.14_7_TEXT", "x3.17_7_TEXT", "x4.10_1_TEXT", "x7.9_6_TEXT") 

for (col in charVars) {
  data[[col]] <- as.character(data[[col]])
}


#for (col in factorVars) {
  #data[[col]] <- as.factor(data[[col]])
#}


allVars <- names(data)
excludeVars <- c(numericVars, charVars, "x1.4")
factorVars <- setdiff(allVars, excludeVars)


for (col in factorVars) {
  data[[col]] <- as.numeric(as.character(data[[col]]))
}





#names(data)
#summary(data)
```


```{r}


# delete over 20 and under 13
data <- data[data$'x2.1' <= 20, ]
data <- data[data$'x2.1' >= 13, ]



# Remove rows where gender is NA or an empty string
data <- data[!is.na(`x2.2`) & `x2.2` != "", ]

# delete in age is is NA or an empty string
data <- data[!is.na(`x2.1`) & `x2.1` != "", ]


```

### Check for weird conditionals
```{r}
#CHECK FOR MALE CONDITIONALS
#change pregnant to NA if indicated Yes and Male
data$'x4.8'[data$'x2.2' == 2 & data$'x4.8' == 1] <- NA

#change menstual to NA if indicated Yes and Male
data$'x3.1'[data$'x2.2' == 2 & (data[["x3.1"]] == 1 | data[["x3.1"]] == 2)] <- NA
# change menstrual age to NA if age and Male
data[["x3.1_1_TEXT"]][data[["x2.2"]] == 2 & data[["x3.1_1_TEXT"]] != ""] <- NA
# change menstrual predict to NA if age and Male
data[["x3.2"]][data[["x2.2"]] == 2 & data[["x3.2"]] != ""] <- NA
data[["x3.3"]][data[["x2.2"]] == 2 & data[["x3.3"]] != ""] <- NA
data[["x3.4"]][data[["x2.2"]] == 2 & data[["x3.4"]] != ""] <- NA
data[["x3.5"]][data[["x2.2"]] == 2 & data[["x3.5"]] != ""] <- NA
data[["x3.6"]][data[["x2.2"]] == 2 & data[["x3.6"]] != ""] <- NA
data[["x3.7"]][data[["x2.2"]] == 2 & data[["x3.7"]] != ""] <- NA
```

```{r}
#CHECK FOR SEX ACTIVITY CONDITIONALS
data[["x3.9"]][data[["x2.2"]] != 1 & data[["x3.9"]] != ""] <- NA



```


```{r}
#query to see duplicate village numbers
sqldf("SELECT [x1.2], COUNT(*) as count 
       FROM data 
       GROUP BY [x1.2] 
       HAVING COUNT(*) > 1")
```


```{r}
#query checker for if male said they were pregnant
sqldf("SELECT [x2.2], [x4.8] , [x1.2]
      FROM data 
      WHERE [x2.2] = 2 AND [x4.8] = 1")
#query for male menstration
sqldf("SELECT [x2.2], [x3.1] 
      FROM data 
      WHERE [x2.2] = 2 AND ([x3.1] = 1 OR [x3.1] = 2)")
#query for male menstration age
sqldf("SELECT [x2.2], [x3.1_1_TEXT]
       FROM data 
       WHERE [x2.2] = 2 AND [x3.1_1_TEXT] != ''")
sqldf("SELECT [x2.2], [x3.2]
       FROM data 
       WHERE [x2.2] = 2 AND [x3.2] != ''")
#3.3,3.4,3.5,3.6,3.7
sqldf("SELECT [x2.2], [x3.7]
       FROM data 
       WHERE [x2.2] = 2 AND [x3.7] != ''")


```
```{r}
# query for sex conditionals
sqldf("SELECT [x3.8], [x3.9]
       FROM data 
       WHERE [x3.8] != 1 AND [x3.9] != ''")

```



### Export clean data and codebook
```{r}
# write new csv of clean data
fwrite(data, "~/Desktop/GRIT/Kibera/cleanedCsv/kibera_values_cleaned.csv")

```

